### ISSUE TITLE
Extend schema for youth organizations

### ISSUE THREAD

**Issue by marians** [netzbegruenung/green-directory#108]
In this issue we track the schema addition to support youth organizations like "Grüne Jugend" (Germany).

### TODO

- [x] Gather some sample data
- [x] Create example entries in the desired format
- [ ] Discuss and agree
- [ ] Provide pull request with adapted schema validation code and some data entries

**Comment by fbthb** [comment]
Sample Data, containing the federal association ("Bundesverband"), all chapters of the federal states ("Landesverbände") und all "Kreisverbände" of Thuringia (Thüringen).
Using a new type YOUTH_ORGANIZATION.
[data.txt](https://github.com/netzbegruenung/green-directory/files/2410022/data.txt)

**Comment by marians** [comment]
@fbthb Looks like we are almost there already!

The type naming `YOUTH_ORGANIZATION` makes sense to me. (Also pinging other contributers to add some eyeballs: @gerbsen @mehlukas @ctr49 @marteb )

Do you want to provide a PR yourself, which

- adapts the validation in [/validate/schema.yaml](https://github.com/netzbegruenung/green-directory/blob/master/validate/schema.yaml) and potentially [/validate/validate.py](https://github.com/netzbegruenung/green-directory/blob/master/validate/validate.py)
- adds the `DE:BUNDESVERBAND` entry to [/data/countries/de/data.yaml](https://github.com/netzbegruenung/green-directory/blob/master/data/countries/de/data.yaml)
- adds the `DE:LANDESVERBAND` entries to the according `/data/countries/de/{state}/data.yaml` files
- adds the `DE:KREISVERBAND` entries for Thüringen to [/data/countries/de/th/data.yaml](https://github.com/netzbegruenung/green-directory/blob/master/data/countries/de/th/data.yaml)

?

Once you send the pull request, the validation will be executed. You can also run it locally using `make validate` once you have set up a Python environment with dependencies.

Some details:

- If there is a `type: TWITTER` attribute in an entry in `urls`, there should also be a `url: <URL>` entry.
- The `---` separator should not have any white space prefixes

**Comment by marians** [comment]
https://github.com/netzbegruenung/green-directory/pull/110 is merged. Closing.
